### ISSUE TITLE
LKRG hide/unhide is incomplete (useless)

### ISSUE THREAD

**Issue by milabs** [Whonix/lkrg#3]
Hi guys,

It's possible to hide LKRG from the modules list using:
`# sudo sysctl -w lkrg.hide=1`

Once hidden, the module is not listed with `lsmod` or `cat /proc/modules` which is fine but it's still possible to detect the presence of LKRG by listing its sysctl's like:
~~~
$ sysctl -A 2>&1 | grep lkrg
sysctl: permission denied on key 'lkrg.block_modules'
sysctl: permission denied on key 'lkrg.heartbeat'
sysctl: permission denied on key 'lkrg.hide'
sysctl: permission denied on key 'lkrg.interval'
sysctl: permission denied on key 'lkrg.kint_enforce'
sysctl: permission denied on key 'lkrg.kint_validate'
sysctl: permission denied on key 'lkrg.log_level'
sysctl: permission denied on key 'lkrg.msr_validate'
sysctl: permission denied on key 'lkrg.pcfi_enforce'
sysctl: permission denied on key 'lkrg.pcfi_validate'
sysctl: permission denied on key 'lkrg.pint_enforce'
sysctl: permission denied on key 'lkrg.pint_validate'
sysctl: permission denied on key 'lkrg.profile_enforce'
sysctl: permission denied on key 'lkrg.profile_validate'
sysctl: permission denied on key 'lkrg.smap_enforce'
sysctl: permission denied on key 'lkrg.smap_validate'
sysctl: permission denied on key 'lkrg.smep_enforce'
sysctl: permission denied on key 'lkrg.smep_validate'
sysctl: permission denied on key 'lkrg.trigger'
sysctl: permission denied on key 'lkrg.umh_enforce'
sysctl: permission denied on key 'lkrg.umh_validate'
~~~

**Comment by savchenko** [comment]
Have you had a chance to check if this can be replicated with the latest upstream? Ping @solardiz .

**Comment by solardiz** [comment]
There's no way this feature can ever be "complete", unless we specify what exactly that means and what it doesn't mean. At this time, the feature is unchanged since @milabs' original issue description here. We have, however, documented the current status of this feature in `README`:

```
- lkrg.hide (0)
  Whether or not LKRG should hide itself from the lists of loaded modules and
  KOBJs.  Allowed values are 0 (do not hide LKRG, or unhide it if previously
  hidden) and 1 (hide LKRG).

  Please note that LKRG can be easily detected by other means anyway, such as
  through the presence of its sysctl's.
```

Arguably, the feature is "complete" in that it already meets its current documentation. Unfortunately, this doesn't make it useful.

If we address the "through the presence of its sysctl's" part, we'll need to edit this paragraph in `README` accordingly (just drop the "such as ..." part or provide another example). Maybe the word "easily" can eventually be dropped, if the remaining ways to detect LKRG are somehow not easy (although on a system where LKRG's protection actually prevents an attack, that very fact is detectable, and likely easily so).

I do find it weird we even have the feature when it's quite useless, so perhaps we should change it one way or the other (make it somewhat less useless, or drop it).

CC: @Adam-pi3

**Comment by adrelanos** [comment]
Quote https://github.com/Whonix/lkrg/blob/master/README.md

> Linux Kernel Runtime Guard (LKRG)
> 
> Linux Kernel Runtime Integrity Checking and Exploit Detection.
> 
> LKRG provides security through diversity. Similar to running an uncommon operating system (kernel) would.
> 
> This is a lightweight software fork [4] of LKRG, with a focus on easy installation, added user documentation, and integration with Whonix [5], Kicksecure [6], Debian [7], and other distributions. The LKRG Debian Package Website can be found here. [8] No changes to or review of the core source code of LKRG. The software fork source code can be found here. [9] Original LKRG upstream can be found here. [10]
> 
>     [4] https://en.wikipedia.org/wiki/Fork_(software_development)
>     [5] https://www.whonix.org
>     [6] https://www.whonix.org/wiki/Kicksecure
>     [7] https://www.debian.org
>     [8] https://www.whonix.org/wiki/Linux_Kernel_Runtime_Guard_LKRG
>     [9] https://github.com/Whonix/lkrg
>     [10] https://www.openwall.com/lkrg/

Therefore such discussions belong upstream, not here.

You're free to discuss this topic here anyhow, but I won't be able to do anything about it.
